ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
MUSIC_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
AUTO_SHIFT_ENABLE = no
LEADER_ENABLE = yes

